### ISSUE TITLE
AttributeError: module 'correlation' has no attribute 'FunctionCorrelation' 

### ISSUE THREAD

**Issue by kwu14victor** [sniklaus/pytorch-liteflownet#51] opened 2023-06-03 02:43 UTC
Hello,

I ran into an error similar to #21, and my environment looks like:

Pytorch 1.13.1
CUDA 11.4.1
Python 3.9.6
GCC 11.2.0
Cupy 11.4.0

Any idea how can I solve this? Thank you!

**Comment by sniklaus** [comment] 2023-06-15 04:45
What does `python -c "print(__import__('torch').version.cuda)"` print?

And what about `python -c "__import__('cupy').show_config()"`?

**Comment by kwu14victor** [comment] 2023-06-16 04:18
Thank you for the response!
I am not familiar with interpreting the results below so I will post the original output, apologies for being lengthy.


The first one printed:
11.4

The second one printed:
OS                           : Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
Python Version               : 3.9.6
CuPy Version                 : 11.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.22.4
SciPy Version                : 1.7.1
Cython Build Version         : 0.29.30
Cython Runtime Version       : 0.29.30
CUDA Root                    : /project/dsi/apps/easybuild/software/CUDA/11.4.1
nvcc PATH                    : /project/dsi/apps/easybuild/software/CUDA/11.4.1/bin/nvcc
CUDA Build Version           : 11040
CUDA Driver Version          : 12010
CUDA Runtime Version         : 11040
cuBLAS Version               : (available)
cuFFT Version                : 10501
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 101201
CUB Build Version            : 101201
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8202
cuDNN Version                : 8202
NCCL Build Version           : 21003
NCCL Runtime Version         : 21003
cuTENSOR Version             : 10601
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-PCIE-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:86:00.0

**Comment by sniklaus** [comment] 2023-06-16 04:25
The environment looks good, and just to confirm this error gets raised when you run:
```
python run.py --model default --one ./images/one.png --two ./images/two.png --out ./out.flo
```

**Comment by kwu14victor** [comment] 2023-06-21 03:40
My apologies but it got raised when I run code from another repo. run.py did not raised this problem with the default model. I will look into that piece of code and maybe open the issue in that repo instead, thank you!

**Comment by sniklaus** [comment] 2023-06-22 06:46
Got it, thanks for clarifying! Sounds like the issue is with how that other repo uses the code herein, I am hence closing this issue but please feel free to reopen it anytime.

**Closed as completed by sniklaus** 2023-06-22 06:46 UTC
