### ISSUE TITLE
The out.flo might be wrong

### ISSUE THREAD

**Issue by steve13durant** [sniklaus/pytorch-liteflownet#32] opened 2020-05-25 03:07 UTC
I used the visualize method to convert flo to png. For pytorch-pwcnet, the result is correct, however the visualization for pytorch-liteflownet is all black picture, there must be something wrong, could you check the result?

**Comment by sniklaus** [comment] 2020-05-25 05:59
Thanks for bringing this up! Would you mind providing more information? What is the `flo` prediction that you got from the code of this repository?

**Comment by steve13durant** [comment] 2020-05-25 14:23
> Thanks for bringing this up! Would you mind providing more information? What is the `flo` prediction that you got from the code of this repository?

Just like I said before, it's a pure black picture after converting out.flo to png.
And the visualization method is  'flow-code.zip' refered from "http://vision.middlebury.edu/flow/submit/"

**Comment by sniklaus** [comment] 2020-05-25 15:53
```
sniklaus@sniklaus:~$ git clone https://github.com/sniklaus/pytorch-liteflownet.git
Cloning into 'pytorch-liteflownet'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 76 (delta 19), reused 32 (delta 12), pack-reused 33
Unpacking objects: 100% (76/76), 1.70 MiB | 12.38 MiB/s, done.
sniklaus@sniklaus:~$ cd pytorch-liteflownet/
sniklaus@sniklaus:~/pytorch-liteflownet$ bash download.bash 
2020-05-25 08:48:19 (8.81 MB/s) - ‘network-default.pytorch’ saved [21576446/21576446]
2020-05-25 08:48:22 (8.40 MB/s) - ‘network-kitti.pytorch’ saved [21576446/21576446]
2020-05-25 08:48:25 (7.58 MB/s) - ‘network-sintel.pytorch’ saved [21576446/21576446]
(base) sniklaus@sniklaus:~/pytorch-liteflownet$ python run.py
(base) sniklaus@sniklaus:~/pytorch-liteflownet$ ~/middlebury/color_flow out.flo out.png
max motion: 36.1942  motion range: u = -7.338 .. 36.185;  v = -4.128 .. 9.837
normalizing by 36.1942
Writing image out.png
```
![out](https://user-images.githubusercontent.com/1238034/82827918-d96dee80-9e64-11ea-8e93-17d8d0df55b9.png)

Works just fine for me. And since you did not want to share your `flo` file with me, I am afraid that I am unable to look into this further. Closing for now, please don't hesitate to share more information to help me reproduce the issue that you are having if you can, thanks!

**Closed as completed by sniklaus** 2020-05-25 15:53 UTC

**Comment by steve13durant** [comment] 2020-05-27 01:38
> ```
> sniklaus@sniklaus:~$ git clone https://github.com/sniklaus/pytorch-liteflownet.git
> Cloning into 'pytorch-liteflownet'...
> remote: Enumerating objects: 43, done.
> remote: Counting objects: 100% (43/43), done.
> remote: Compressing objects: 100% (31/31), done.
> remote: Total 76 (delta 19), reused 32 (delta 12), pack-reused 33
> Unpacking objects: 100% (76/76), 1.70 MiB | 12.38 MiB/s, done.
> sniklaus@sniklaus:~$ cd pytorch-liteflownet/
> sniklaus@sniklaus:~/pytorch-liteflownet$ bash download.bash 
> 2020-05-25 08:48:19 (8.81 MB/s) - ‘network-default.pytorch’ saved [21576446/21576446]
> 2020-05-25 08:48:22 (8.40 MB/s) - ‘network-kitti.pytorch’ saved [21576446/21576446]
> 2020-05-25 08:48:25 (7.58 MB/s) - ‘network-sintel.pytorch’ saved [21576446/21576446]
> (base) sniklaus@sniklaus:~/pytorch-liteflownet$ python run.py
> (base) sniklaus@sniklaus:~/pytorch-liteflownet$ ~/middlebury/color_flow out.flo out.png
> max motion: 36.1942  motion range: u = -7.338 .. 36.185;  v = -4.128 .. 9.837
> normalizing by 36.1942
> Writing image out.png
> ```
> 
> ![out](https://user-images.githubusercontent.com/1238034/82827918-d96dee80-9e64-11ea-8e93-17d8d0df55b9.png)
> 
> Works just fine for me. And since you did not want to share your `flo` file with me, I am afraid that I am unable to look into this further. Closing for now, please don't hesitate to share more information to help me reproduce the issue that you are having if you can, thanks!

I redownloaded the model, and it solved my problem. Thank you very much!

**Comment by sniklaus** [comment] 2020-05-27 01:46
Thanks for the update, I am happy it is working for you now!
